"""
starters/changelog-drafter/run.py

Reads git commits since the last tag and drafts a CHANGELOG entry.
Always human-reviewed — never auto-merges.

Usage:
  python starters/changelog-drafter/run.py
  python starters/changelog-drafter/run.py --since v1.2.0
"""

import argparse
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from loop_engine import LoopRunner


def get_git_log(since_ref: str = "") -> str:
    """Get commits since last tag or a specific ref."""
    if not since_ref:
        # find last tag
        result = subprocess.run(
            ["git", "describe", "--tags", "--abbrev=0"],
            capture_output=True, text=True,
        )
        since_ref = result.stdout.strip() if result.returncode == 0 else "HEAD~30"

    result = subprocess.run(
        ["git", "log", f"{since_ref}..HEAD", "--oneline", "--no-merges"],
        capture_output=True, text=True,
    )
    return result.stdout.strip() or "(no commits found)"


class ChangelogDrafter(LoopRunner):

    def draft(self, since_ref: str = "") -> str:
        git_log = get_git_log(since_ref)
        if "(no commits found)" in git_log:
            print("[changelog] No new commits since last tag.")
            return ""

        print(f"[changelog] {len(git_log.splitlines())} commits to summarise.")

        system = self.skills.inject(
            "You are a technical writer drafting a CHANGELOG.",
            "changelog",
        )
        draft = self.llm.chat(
            f"Draft a CHANGELOG entry from these git commits:\n\n{git_log}",
            system=system,
        )

        # write draft for human review
        draft_path = Path("CHANGELOG_DRAFT.md")
        draft_path.write_text(
            f"<!-- Draft generated by changelog-drafter loop. Review before adding to CHANGELOG.md -->\n\n"
            f"{draft}\n"
        )
        print(f"[changelog] Draft written to {draft_path}")
        print("[changelog] Review it, edit as needed, then append to CHANGELOG.md.")
        return draft


def main():
    parser = argparse.ArgumentParser(description="Changelog Drafter")
    parser.add_argument("--since", default="", help="Git ref to start from (default: last tag)")
    args = parser.parse_args()

    drafter = ChangelogDrafter()
    drafter.draft(since_ref=args.since)


if __name__ == "__main__":
    main()
